version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - "./selenoid/browsers.json:/etc/browsers.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 5s
      timeout: 5s
      retries: 5

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    depends_on:
      selenoid:
        condition: service_healthy  # Ждем готовности selenoid
    ports:
      - "8081:8080"
    networks:
      - selenoid_net
    command: ["--selenoid-uri", "http://selenoid:4444"]

  test_docker:
    build: .
    container_name: test_docker
    depends_on:
      selenoid:
        condition: service_healthy  # Ждем готовности selenoid
    networks:
      - selenoid_net
    environment:
      SELENOID_URI: http://selenoid:4444/wd/hub
      BROWSER: chrome
    volumes:
      - ./reports:/app/reports
    command: ["pytest", "-v", "--alluredir=/app/reports/allure-results"]

networks:
  selenoid_net:
    name: selenoid_net  # Фиксированное имя сети
    driver: bridge